language: node_js
sudo: required
dist: xenial
node_js:
  - 12

addons:
  snaps:
  - name: snapcraft
    confinement: classic

cache:
  directories:
    - packages/e-app/node_modules
    - packages/e-server/node_modules
    - packages/e-web/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - curl -sf https://gobinaries.com/tj/robo | sh
  - cd packages/e-web && npm i && cd -
  - cd packages/e-server && npm i && cd -
  - cd packages/e-app && npm i && cd -
  - cd packages/e-server
  - npm i && npm run dist
  - cd -
  - robo desktop-build

deploy:
  provider: releases
  api_key:
    secure: "ZDHiOfYSjnvKzspApyfEuzN0B684ewC63nLLSUBCFxXRiLbVwWIQaw6bLLacYL16K3pIx+F8d9ex0u1DJCX0hogZkUh5a+UG5+pUUZJrSIOK5Lpg6pR0txTkYIdvx6H/XNLW0wNfmA5VGtls51fFR3YfYzBlw8c8qW/axtTHF4UNCmnR7kh9Fq/QjQL+QLh8helzxrnU99aWBp2emqKNVBb3TlxPzz0lUI3O9oUC9zLAP7To/4jxx7Uy07DA/WXze3No6BgOrHZT+R4ObcKFri6fwaqzKyUVwKoSznnlU9Sm3rkorZB3sn26hoNjNIBpbmV3R6LkevzkuCqJo5oFL5CaYOgKlia7ESJWYLvLOa6/bz3YM43im0lYoVcsud6ceX6p+bZdFRqxnp8Ssm/knN95j+kGB7CGvAMuDugd/EzOcVeS/2k+vr3LJfSJM+tEbXuXtJ3OVoNIAigwiXd6f1SlND+RkP6J31KlGTKWeAy6/8glAJmS/IWYtVCyc7lX06WiyswEkPKLoRvYlCXVSJj1GA7f5HJ8hNCPVF+A4NPJHC+LfLhkwdJM+6F9qxV0YQbnvp5Oczk5821n2lzxm8kESSVW/1qTaM3AWI6DpwifZaFcVqvMWf455/J3/Hlby9ylg+UL+2rTKjJPmDwXdQP+dMGRtJUChvDv+7J7N0A="
  file: packages/e-server/dist/rep2recall-local-server-linux-x64
  skip_cleanup: true
  draft: true

branches:
  - master