FROM node:12-alpine AS server
RUN npm i -g pnpm
WORKDIR /app
COPY packages/server/package.json packages/server/pnpm-lock.yaml ./
RUN pnpm i --prod --frozen-lockfile

FROM astefanutti/scratch-node:12
WORKDIR /app
COPY --from=server /app/node_modules node_modules
COPY packages/server/dist dist
COPY packages/web/dist public
EXPOSE 8080
ENTRYPOINT ["node", "dist/index.js"]
