version: '3'
services:
  app:
    restart: always
    image: patarapolw/rep2recall
    # build:
    #   context: packages/server
    #   dockerfile: Dockerfile
    ports:
      - '36323:36323'
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/rep2recall
      - PORT=36323
      - DEFAULT_USER
      - SECRET=qtvov0meacVNh4HwAq5FZEcSpbwZ6ywJ
      - MAGIC_SECRET
      - MAGIC_PUBLIC
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
